/**
 * Curated list of differentiating questions.
 *
 * Selection criteria (StemWijzer-style):
 * - stdev of candidate stances >= 1.0 (significant disagreement across candidates)
 * - at least 4 candidates have documented positions
 * - max 3 questions per category (ensures diversity)
 * - at least 1 question from each of the 14 categories
 *
 * Generated by scripts/select-questions analysis on 2026-04-19.
 * Total: 27 questions covering all 14 categories.
 */
export const SELECTED_QUESTION_IDS = [
  // politica_exterior (2)
  "ext-03",
  "ext-01",
  // agricultura (2)
  "agr-06",
  "agr-01",
  // justicia (1)
  "jus-03",
  // economia (3)
  "econ-05",
  "econ-01",
  "econ-02",
  // seguridad (3)
  "seg-01",
  "seg-03",
  "seg-07",
  // trabajo (3)
  "tra-02",
  "tra-05",
  "tra-06",
  // energia (3)
  "ene-04",
  "ene-01",
  "ene-05",
  // salud (2)
  "sal-01",
  "sal-05",
  // medio_ambiente (2)
  "amb-04",
  "amb-01",
  // cultura (2)
  "cul-06",
  "cul-04",
  // comercio_exterior (1)
  "com-01",
  // educacion (1)
  "edu-01",
  // tecnologia (1)
  "tec-03",
  // vivienda (1)
  "viv-01",
] as const;

export const SELECTED_IDS_SET = new Set<string>(SELECTED_QUESTION_IDS);
